// This file is the public API of @agora/db
// database.types.ts is generated by the Supabase CLI and must not be edited manually.
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > packages/db/src/database.types.ts
export type { Database } from './database.types'
