import { OpenApiGeneratorV31 } from '@asteasolutions/zod-to-openapi'
import { z } from 'zod'
import { registry } from './registry'

// ── /keys/request ────────────────────────────────────────────────────────────
registry.registerPath({
  method:  'post',
  path:    '/keys/request',
  summary: 'Request a free API key',
  description: [
    'Submit your email and a description of your intended use.',
    'Returns a new API key — shown once and never stored in plain text.',
    'Include the key on subsequent requests as: Authorization: Bearer agora_...',
  ].join(' '),
  tags: ['Authentication'],
  request: {
    body: {
      required: true,
      content: {
        'application/json': {
          schema: z.object({
            email:       z.string().email().openapi({ example: 'journalist@dn.se' }),
            description: z.string().min(20).max(500).openapi({
              example: 'Building an election tracker for DN.se readers.',
            }),
          }),
        },
      },
    },
  },
  responses: {
    200: { description: 'API key created — store the key field, it is shown only once' },
    400: { description: 'Validation error or key limit reached' },
  },
})

// ── /accountability ───────────────────────────────────────────────────────────
registry.registerPath({
  method:  'get',
  path:    '/accountability',
  summary: 'Cross-source accountability arc for a party and topic',
  description: [
    'Returns the complete accountability arc across four data layers:',
    'manifesto promises, legislation filed, voting record, and budget outcomes.',
    'Also includes a ≤150-word Swedish synthesis generated by Claude Sonnet.',
    'Requires a valid API key (Authorization: Bearer agora_...).',
  ].join(' '),
  tags: ['Accountability'],
  security: [{ BearerAuth: [] }],
  request: {
    query: z.object({
      party: z.string().min(1).max(4).openapi({ example: 'S', description: 'Party code (S, M, SD, C, V, KD, L, MP)' }),
      topic: z.string().min(3).max(200).openapi({ example: 'klimat', description: 'Topic to analyse (Swedish free text)' }),
    }),
  },
  responses: {
    200: { description: 'Accountability data with all four layers and optional AI summary' },
    400: { description: 'Unknown party code or invalid params' },
    401: { description: 'Missing or invalid API key' },
    403: { description: 'API key revoked' },
    429: { description: 'Rate limit exceeded' },
  },
})

// ── /parties/{party}/alignment ────────────────────────────────────────────────
registry.registerPath({
  method:  'get',
  path:    '/parties/{party}/alignment',
  summary: 'Manifesto position breakdown by Manifesto Project category',
  description: [
    'Returns aggregated manifesto positions for the most recent election year,',
    'grouped by Manifesto Project category code. No API key required.',
  ].join(' '),
  tags: ['Parties'],
  request: {
    params: z.object({
      party: z.string().openapi({ example: 'MP', description: 'Party code' }),
    }),
  },
  responses: {
    200: { description: 'Category breakdown with mean_position per category' },
    404: { description: 'Unknown party code' },
  },
})

export function generateOpenApiSpec() {
  const generator = new OpenApiGeneratorV31(registry.definitions)
  return generator.generateDocument({
    openapi: '3.1.0',
    info: {
      title:       'Agora API',
      description: 'Swedish political data API — motioner, ledamöter, voteringar, budget, valmanifest',
      version:     '1.0.0',
      contact:     { url: 'https://agora.se' },
      license:     { name: 'CC0 1.0', url: 'https://creativecommons.org/publicdomain/zero/1.0/' },
    },
    servers: [{ url: 'https://agora.se/api/v1' }],
  })
}
